apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: cilium-cni
spec:
  clusterSelector:
    # Target workload clusters with specific labels.
    matchLabels:
      ciliumCNI: enabled
  releaseName: cilium
  repoURL: https://helm.cilium.io/
  chartName: cilium
  namespace: kube-system
  valuesTemplate: |
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
    ipam:
      mode: "cluster-pool"
      operator:
        clusterPoolIPv4PodCIDRList:{{range $i, $cidr := .Cluster.spec.clusterNetwork.pods.cidrBlocks }}
          - {{ $cidr }}{{end}}
    cluster:
      name: {{ .Cluster.metadata.name }}
      id: {{ (atoi .Cluster.metadata.annotations.clusterID) }}
    clustermesh:
      useAPIServer: true
      apiserver:
        kvstoremesh:
          enabled: false
        service:
          type: NodePort
          nodePort: {{ add 32000 (atoi .Cluster.metadata.annotations.clusterID) }}
    operator:
      replicas: 1
      rollOutPods: true
    rollOutCiliumPods: true
    kubeProxyReplacement: true
    kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
    k8sServiceHost: {{ .Cluster.spec.controlPlaneEndpoint.host }}
    k8sServicePort: {{ .Cluster.spec.controlPlaneEndpoint.port }}
