apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: cilium-cni
spec:
  clusterSelector:
    # Target workload clusters with specific labels.
    matchLabels:
      ciliumCNI: enabled
  releaseName: cilium
  repoURL: https://helm.cilium.io/
  chartName: cilium
  namespace: kube-system
  valuesTemplate: |
    ipam:
      mode: "kubernetes"
    cluster:
      name: {{ .Cluster.metadata.name }}
      id: {{ (atoi .Cluster.metadata.annotations.clusterID) }}
    operator:
      replicas: 1
      rollOutPods: true
    rollOutCiliumPods: true
    kubeProxyReplacement: false
    k8sServiceHost: {{ .Cluster.spec.controlPlaneEndpoint.host }}
    k8sServicePort: {{ .Cluster.spec.controlPlaneEndpoint.port }}
