apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: cilium-cni
spec:
  clusterSelector:
    # Target workload clusters with specific labels.
    matchLabels:
      ciliumCNI: enabled
  releaseName: cilium
  repoURL: https://helm.cilium.io/
  chartName: cilium
  namespace: kube-system
  valuesTemplate: |
    ipam:
      mode: "cluster-pool"
      operator:
        clusterPoolIPv4PodCIDRList:{{range $i, $cidr := .Cluster.spec.clusterNetwork.pods.cidrBlocks }}
          - {{ $cidr }}{{end}}
    operator:
      replicas: 1
      rollOutPods: true
    rollOutCiliumPods: true
    securityContext:
      privileged: true
      capabilities:
        ciliumAgent:
          - PERFMON
          - BPF
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUI
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
