---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capi-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: kamaji
  interval: 5m
  retryInterval: 30s
  timeout: 4m
  wait: true
  path: ./test/capi-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
