---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capi-clusterclass
  namespace: flux-system
spec:
  dependsOn:
    - name: capi-operator
  interval: 5m
  retryInterval: 30s
  timeout: 4m
  wait: true
  path: ./test/cluster-class
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
