---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kamaji
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 5m
  retryInterval: 30s
  timeout: 4m
  wait: true
  path: ./test/kamaji
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
