---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubevirt
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 30s
  timeout: 4m
  path: ./test/kubevirt
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
